### ISSUE TITLE
bug: TroubleNormal is not great with folkes/trouble

### ISSUE THREAD

**Issue by vincentsegard** [craftzdog/solarized-osaka.nvim#11]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

Hello,

TroubleNormal makes diagnostics's window from folke/trouble really weird, difficult to read, I commented the line with TroubleNormal in LspTrouble and it looks much better.
![image](https://github.com/craftzdog/solarized-osaka.nvim/assets/69211483/0cb31d01-724a-41e3-8b20-a11de16000a5)

Thank you

### Steps To Reproduce

Install folke/trouble.nvim and open diagnostics with :TroubleToggle

### Expected Behavior

Readable LspTrouble diagnostic window by changing colors of TroubleNormal
![image](https://github.com/craftzdog/solarized-osaka.nvim/assets/69211483/1ad23215-cb6a-4ff8-97fa-39398b021a2f)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/trouble.nvim",
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by craftzdog** [comment]
thanks for reporting
