### ISSUE TITLE
feature: Make it look good with Lualine

### ISSUE THREAD

**Issue by TinusgragLin** [craftzdog/solarized-osaka.nvim#12]
### Did you check the docs?

- [X] I have read all the solarized-osaka.nvim docs

### Is your feature request related to a problem? Please describe.

I am using this fantastic colorscheme with Lualine and I noticed that (the diff and diagnostics status part of) `b` section of Lualine looks quite unpleasant:
![2024-01-21_21-43-24](https://github.com/craftzdog/solarized-osaka.nvim/assets/57218218/a296a800-b750-49d4-ac2c-86914033403f)

### Describe the solution you'd like

I think that we can change the `normal.b.bg` to make the whole thing look better. Changing foreground colors can also be done but involves more changes (e.g. setting [`LuaLineDiffAdd` `LuaLineDiffChange` and `LuaLineDiffDelete`](https://github.com/nvim-lualine/lualine.nvim/blob/566b7036f717f3d676362742630518a47f132fff/lua/lualine/components/diff/init.lua#L22) and changing [diagnostic colors](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/diagnostics/config.lua#L30)).

### Describe alternatives you've considered

(None)

**Comment by TinusgragLin** [comment]
I see that we set `normal.b.bg` to `colors.fg` [here](https://github.com/craftzdog/solarized-osaka.nvim/blob/e436a77eb643fe42d52b229c5cdf2e72dda88ed4/lua/lualine/themes/solarized-osaka.lua#L8), maybe we should change it to a darker variant?

**Comment by craftzdog** [comment]
yes, can you make a pr?

**Comment by TinusgragLin** [comment]
> yes, can you make a pr?

The pr is just open!
