### ISSUE TITLE
highlight group for nvim-bqf preview window

### ISSUE THREAD

**Issue by gennaro-tedesco** [craftzdog/solarized-osaka.nvim#15]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2048+g367e52cc7-Homebrew

### Operating system/version

MacOs Venture 13.6.1

### Describe the bug

I am using [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) and have troubles rendering the preview window background highlight with the same background colour as the normal buffer. In particular, the window colour seems to default to a darker shade as in the screenshot below:

![Screenshot 2024-01-29 at 15 45 41](https://github.com/craftzdog/solarized-osaka.nvim/assets/15387611/5aff28fe-e65f-4e54-b7f9-7e4495a58a1c)

I have checked the definitions of the [theme colour highlight groups](https://github.com/craftzdog/solarized-osaka.nvim/blob/83b7026ac7a4e185d4ecbe99926fd94b5735e2ea/lua/solarized-osaka/theme.lua) but I cannot seem to find the correct one that applies to it (I tried `BufferAlternate/BufferInactive` and so forth). 

To reproduce I am using the following configuration
```lua
{
"craftzdog/solarized-osaka.nvim",
lazy = false,
priority = 1000,
opts = {
	transparent = true,
	styles = {
		keywords = { italic = false },
		sidebars = "transparent",
		floats = "transparent",
	},
},
init = function()
	vim.cmd([[colorscheme solarized-osaka]])
end,
}
```

What is the specific highlight group to modify in this case?

P. S. I have tried changing `sidebars/floats` option values to no avail.

### Steps To Reproduce

1. use the configuration provided above
2. open the quickfix window
3. colours default to a darker shade than the normal buffer

### Expected Behavior

The background colour of the nvim-bqf preview window is as the normal buffer.

**Comment by TinusgragLin** [comment]
I haven't tried nvim-bqf. However when I was using [fidget.nvim](https://github.com/j-hui/fidget.nvim) with transparent background colorschemes, I also noticed that the notification window of fidget.nvim turns black, after some digging, I found that there is an option [`winblend`](https://neovim.io/doc/user/options.html#'winblend') for a float window and setting it to `0` solves the problem. In my case, fidget.nvim does have an option to set the default `winblend` for all notification window it uses, and after a quick check, [nvim-bqf has it as well](https://github.com/kevinhwang91/nvim-bqf/blob/bdc2a4e5bb670b3c0e33ada9c0eec636d93a0748/lua/bqf/config.lua#L19). @gennaro-tedesco Can you try to set it to 0 to see whether it solves the problem?

**Comment by gennaro-tedesco** [comment]
@TinusgragLin You are perfectly right, setting the `winblend` to 0 does it. Thank you for the hint, we can consider this issue addressed and solved :)
