### ISSUE TITLE
How to change theme transparency

### ISSUE THREAD

**Issue by Abrillant-Lee** [craftzdog/solarized-osaka.nvim#16]
When using this theme, you may occasionally encounter situations where the background is white and the content cannot be seen clearly.![image](https://github.com/craftzdog/solarized-osaka.nvim/assets/129536239/6bf9587b-a8bb-4583-b0f7-c9719b5d34c6)

**Comment by Touil-Ali** [comment]
To Replace Transparency change `transparent` option 
```lua
require("solarized-osaka").setup({
  transparent = false,
```
here's how i do it in lazy vim 
``` lua 
{
    "craftzdog/solarized-osaka.nvim",
    lazy = false,
    priority = 1000,
    opts = function()
      return {
        transparent = false,
      }
    end,
  },
```
