### ISSUE TITLE
bug: undercurl when using rust on println! commands

### ISSUE THREAD

**Issue by Redoxahmii** [craftzdog/solarized-osaka.nvim#19]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Arch Linux

### Describe the bug

When using this color scheme in a rust file it shows an undercurl on println! like commands and other statements too
![Screenshot from 2024-02-20 23-09-49](https://github.com/craftzdog/solarized-osaka.nvim/assets/13983258/a1cbb01a-8ebd-43af-9025-15bca672b889)
![Screenshot from 2024-02-20 23-09-19](https://github.com/craftzdog/solarized-osaka.nvim/assets/13983258/c6ed84eb-49d5-4cd7-b729-735215b6ba0c)

You can see here that the same issue does not reproduce if you are using Catppuccin.
The issue is also present in [tokyonight.nvim](https://github.com/folke/tokyonight.nvim) so i'm currently clueless to why this is happening in these 2 themes.

### Steps To Reproduce

1. create a .rs file and use println! statements.

### Expected Behavior

Should not show the undercurl.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by Redoxahmii** [comment]
I just noticed in the branches of the project that you have used [tokyonight](https://github.com/folke/tokyonight.nvim) as the base and the issues is also present in that colorscheme in rust so that might be the underlying issue.

**Comment by craftzdog** [comment]
Can you also report it to tokyonight.nvim? I don't have time to fix it atm but can port the patch into this repo.

**Comment by Redoxahmii** [comment]
There seems to be a recent [issue](https://github.com/folke/tokyonight.nvim/issues/496) created for this on tokyonight too after i discussed this on reddit. Let's see how much time it takes for that to resolve.

**Comment by Redoxahmii** [comment]
SOLUTION: The solution to this was to use `rustup` and install the stable tool chain but if you are still using the `rust` package the issue remains.
I am not closing the issue but provided the info if someone else might run into this issue.
