### ISSUE TITLE
bug: `on_highlights` option is not working

### ISSUE THREAD

**Issue by leonasdev** [craftzdog/solarized-osaka.nvim#2]
### Did you check docs and existing issues?

- [X] I have read all the tokyonight.nvim docs
- [X] I have searched the existing issues of tokyonight.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

`on_highlight` options is not working when set.

It's seems the function is commented by accident?

https://github.com/craftzdog/solarized-osaka.nvim/blob/fc7e1a0ff81adca26c1b4e5c45049a09c0ae30a1/lua/solarized-osaka/theme.lua#L811

### Steps To Reproduce

1. Set `on_highlight` option when call `require("solarized-osaka").setup()`

### Expected Behavior

The specific highlight group should be overwritten when the `on_highlight` callback was set.

**Comment by tigion** [comment]
I noticed the same thing. The use of `on_highlights` is ignored.

```lua
return {
  'craftzdog/solarized-osaka.nvim',
  lazy = false,
  priority = 1000,
  opts = {
    styles = {
      sidebars = 'transparent',
    },
    on_highlights = function(hl, c)
      hl.AlphaHeader = { fg = c.orange }
    end,
  },
  config = function(_, opts)
    require('solarized-osaka').setup(opts)
    vim.cmd [[colorscheme solarized-osaka]]
  end,
}
```

**Comment by tigion** [comment]
I noticed the same thing. The use of `on_highlights` is ignored.

```lua
return {
  'craftzdog/solarized-osaka.nvim',
  lazy = false,
  priority = 1000,
  opts = {
    styles = {
      sidebars = 'transparent',
    },
    on_highlights = function(hl, c)
      hl.AlphaHeader = { fg = c.orange }
    end,
  },
  config = function(_, opts)
    require('solarized-osaka').setup(opts)
    vim.cmd [[colorscheme solarized-osaka]]
  end,
}
```

**Comment by craftzdog** [comment]
#3 fixed the issue
