### ISSUE TITLE
feature: An option or highlight group to set lualine section (a, b, c) colors

### ISSUE THREAD

**Issue by tigion** [craftzdog/solarized-osaka.nvim#20]
### Did you check the docs?

- [X] I have read all the solarized-osaka.nvim docs

### Is your feature request related to a problem? Please describe.

I like more the older (2nd lualine in screenshot) variant, in which section b has a different color than section c.

<img width="439" alt="solarized-osaka-lualine" src="https://github.com/craftzdog/solarized-osaka.nvim/assets/31811/0c4e6e7f-991e-4da3-9f37-d31a0a88b25b">

Is there a way to customize this via the config/opts for solarized-osaka?

I know there is an issue #12 in which section b was matched to the color of section c. But now the difference between section b and c has disappeared.

### Describe the solution you'd like

An option or highlight group, alternatively a tip on how I can achieve this using the available options.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by tigion** [comment]
My current workaround is to customize the `lualine.themes.solarized-osaka` theme directly in my _lualine.lua_ configuration:

```lua
-- custom solarized-osaka section colors
local colors = require('solarized-osaka.colors').setup({ transform = true })
local custom_theme = require('lualine.themes.solarized-osaka')
custom_theme.normal.b.fg = colors.black
custom_theme.normal.b.bg = colors.fg
```

**Comment by craftzdog** [comment]
the 'b' section was not right. thanks
