### ISSUE TITLE
feature: Single color selection

### ISSUE THREAD

**Issue by jblyberg** [craftzdog/solarized-osaka.nvim#23]
### Did you check the docs?

- [X] I have read all the solarized-osaka.nvim docs

### Is your feature request related to a problem? Please describe.

Selection highlighting is hard to read.

### Describe the solution you'd like

I find that selected text is too jumbled with all the different colors. Ideally, selected text would work like other themes where it's a single color, semi-transparent with the original highlight colors coming through.

### Describe alternatives you've considered

I'm sure there is a way to overwrite those colors, but I'm not familiar enough with how theme colors work in nvim.

**Comment by craftzdog** [comment]
Use `on_colors` option

**Comment by jblyberg** [comment]
Got it. 

For anyone looking for a solution to this, here's what I did:

```lua
  {
    "craftzdog/solarized-osaka.nvim",
    config = function()
      require("solarized-osaka").setup({
        transparent = true,
        on_highlights = function(highlights, colors)
          highlights.Visual = { bg = colors.base03, reverse = false }
        end,
      })
    end,
  },
```
