### ISSUE TITLE
bug: Winbar background flash

### ISSUE THREAD

**Issue by BBboy01** [craftzdog/solarized-osaka.nvim#26]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

14.3.1

### Describe the bug

Using (lspsaga](https://github.com/nvimdev/lspsaga.nvim) with breadcrumb, Winbar background flash while cursor moves around empty line or function call and statement

### Steps To Reproduce

https://github.com/craftzdog/solarized-osaka.nvim/assets/59885141/000998e5-e048-4a13-8a2b-a1a273ff0e9f

function call with winbar background
![CleanShot 2024-03-07 at 12 47 59@2x](https://github.com/craftzdog/solarized-osaka.nvim/assets/59885141/5dc2f10b-80ab-4001-a36a-015d1cbb7809)

empty line with winbar background
![CleanShot 2024-03-07 at 12 48 14@2x](https://github.com/craftzdog/solarized-osaka.nvim/assets/59885141/9391f60f-f506-47b1-a23e-34db21a1d85f)

statment without background
![CleanShot 2024-03-07 at 12 48 23@2x](https://github.com/craftzdog/solarized-osaka.nvim/assets/59885141/c9a95f19-cf99-4e49-bc1c-b0d278672b52)

### Expected Behavior

always with/without background color

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
  "nvimdev/lspsaga.nvim"
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by craftzdog** [comment]
it is nothing to do with this theme

**Comment by BBboy01** [comment]
has been fixed by https://github.com/nvimdev/lspsaga.nvim/pull/1410
