### ISSUE TITLE
bug: Underline on every word.

### ISSUE THREAD

**Issue by Redoxahmii** [craftzdog/solarized-osaka.nvim#34]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

I just updated to Neovim 0.10 and every word has an underline being shown below. 
For other modern colorschemes like Tokyonight it shows a shading instead of an underline and this did not happen before 0.10.

### Steps To Reproduce

1. Enable solarized-osaka as colorscheme
2. Put cursor on any word.

### Expected Behavior

Shading instead of underlining as it was in v0,95

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by Redoxahmii** [comment]
For reference this is what it looks like:
![t_2024_05_21_06_42](https://github.com/craftzdog/solarized-osaka.nvim/assets/13983258/48bc5bfc-8abe-43dd-bb47-d89f4ed8d8f4)

**Comment by craftzdog** [comment]
thanks for reporting
