### ISSUE TITLE
bug: leap.nvim labels do not work in visual mode

### ISSUE THREAD

**Issue by zerdaks** [craftzdog/solarized-osaka.nvim#42]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.0.1

### Describe the bug

When using leap.nvim, after typing the first character of a two character search, "labels" should appear next to some of the {char1}{?} pairs. This is currently not working.

**Proposed solution**: replace `LeapLabelPrimary` and `LeapLabelSecondary` in https://github.com/craftzdog/solarized-osaka.nvim/blob/126d394c0c979a99206214a2b6b8c86e456c9c0f/lua/solarized-osaka/theme.lua#L625-L626 with:

`LeapLabel = { fg = c.magenta500, bold = true }`

See [catppuccin](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/leap.lua) for more context.

### Steps To Reproduce

1. Install the plugin leap.nvim
2. Open a file and search for a term

### Expected Behavior

After typing the first character of a two character search, "labels" should appear next to some of the {char1}{?} pairs.

**Comment by craftzdog** [comment]
Looks like the label names have been changed.

https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/groups/leap.lua

Can you make a PR?
