### ISSUE TITLE
feature: support neovide

### ISSUE THREAD

**Issue by swimablefish** [craftzdog/solarized-osaka.nvim#45]
### Did you check the docs?

- [X] I have read all the solarized-osaka.nvim docs

### Is your feature request related to a problem? Please describe.

I try [neovide](https://neovide.dev/) recently for some cases. The theme works well with nvim as below
![solarized-osaka in nvim](https://github.com/user-attachments/assets/6dd1be8d-87b1-4641-bf05-61b13e5514cd)
But it doesn't work with neovide.
![solarized-osaka in neovide](https://github.com/user-attachments/assets/0087b47a-5508-4615-a9eb-b991f19cb80a)

Can solarized-osaka support neovide? Thanks, :)

### Describe the solution you'd like

The neovide can show the correct color with solarized-osaka

### Describe alternatives you've considered

NA

**Comment by craftzdog** [comment]
You can send a PR

**Comment by swimablefish** [comment]
Just setting `transparent` as `false` works. Thanks.
