### ISSUE TITLE
feature: Add blink.cmp hl groups

### ISSUE THREAD

**Issue by Redoxahmii** [craftzdog/solarized-osaka.nvim#47]
### Did you check the docs?

- [X] I have read all the solarized-osaka.nvim docs

### Is your feature request related to a problem? Please describe.

`blink.cmp` provides option to use `nvim-cmp` hl groups for the time being but that is marked as something that will be removed in the future.
Currently if you are using it with that behavior a lot of colors are not working properly and the completion menu does not seem to be slightly transparent but instead renders as solid color.
Also the windows that show additional help related to an entry are also transparent and exhibiting such behavior making it difficult to use.

### Describe the solution you'd like

Properly styled hl groups so the behavior is consistent.

### Describe alternatives you've considered

Styled some to use for the time being but the menu issues i could not figure out.
My guess is that float windows that appear for menu and the additional info windows use different attributes compared to what `nvim-cmp` might be using.
`BlinkCmp` highlight group for `blink.cmp` uses `NormalFloat` for documentation windows which might be different from what `nvim-cmp` uses but couldn't find exactly what `nvim-cmp` is using.H
Similarly the completion menu window `BlinkCmpMenu` highlight is a `PMenu` which might be different from `nvim-cmp` defaults.

### Additional context

I can make a pull request with defaults as same as `nvim-cmp` but the types of windows and their different behaviors are something I'm not knowledgeable about so better for someone who understands it to implement.

**Comment by craftzdog** [comment]
Hey, @Redoxahmii! Thanks so much for your contributions to this theme.

I'm currently busy with my project and can't find spare time to maintain the theme at the moment.
I'd be happy to welcome you as a collaborator of this repository.
I've sent an invitation, so please join it if you are interested.

There is absolutely no problem with adding blink.cmp.
Just like TokyoNight.nvim, it'd be nice to do some refactoring to split `theme.lua` into groups:
https://github.com/folke/tokyonight.nvim/tree/main/lua/tokyonight/groups

**Comment by Redoxahmii** [comment]
Thank you for the invite.
I had some issue with how the colors were being displayed when working with `blink.cmp` but for the time being I will add the colors so they are the same as `nvim-cmp`.
Could you please tell how I should push code now i would prefer not pushing into the repo directly but create a pull request so we both can take a look before it gets pushed into main.
Or I can create a separate branch in the main project where I could implement and than merge later.

**Comment by Redoxahmii** [comment]
For the refactoring part I will take a look into tokyonight and if it seems probable create a pull for it.

**Comment by craftzdog** [comment]
You can create PRs and merge them freely if they are minor changes, so I can quickly track the changes you made.
If you would like to make a major change or something that you think would need my review like the refactoring work, add me as a reviewer in the PR.

**Comment by craftzdog** [comment]
fixed in https://github.com/craftzdog/solarized-osaka.nvim/pull/49
