### ISSUE TITLE
feature: Compatibility with mini.nvim [specifically mini-statusline]

### ISSUE THREAD

**Issue by Numkil** [craftzdog/solarized-osaka.nvim#5]
### Did you check the docs?

- [X] I have read all the tokyonight.nvim docs

### Is your feature request related to a problem? Please describe.

I love the colorscheme you have created and I would love to use it but i've built a setup around mini.nvim and this colorscheme is incompatible with mini-statusline. The middle part of the statusline is completely grayed out instead of correctly displaying the filename. See screenshot.

![Screenshot 2023-11-27 at 09 19 11](https://github.com/craftzdog/solarized-osaka.nvim/assets/5604686/30e84573-7b13-4881-aa2f-0f5091eac37f)

### Describe the solution you'd like

If you are interested and have the time I would be very happy if you could add compatibility for mini-statusline in this project that way i could switch over to this colorscheme permanently. 

### Describe alternatives you've considered

Maybe you could share a way how i could resolve this issue using the on_colors or on_highlights functionality of your plugin.

**Comment by craftzdog** [comment]
PR would be appreciated
The highlights are defined here https://github.com/craftzdog/solarized-osaka.nvim/blob/83b7026ac7a4e185d4ecbe99926fd94b5735e2ea/lua/solarized-osaka/theme.lua#L713

**Comment by soullessness1611** [comment]
Hi Takuya Matsuyama,

I love your colorscheme a lot of, but i would link to remove highlight yellow background as below figure, Can you provide how to remove it?

Thank you very much.

![2024-01-18_22-58-23](https://github.com/craftzdog/solarized-osaka.nvim/assets/131554043/20bb4f4a-d0c8-4a47-8a89-afde30082c20)

**Comment by TinusgragLin** [comment]
Hey, I think that this can be closed after https://github.com/craftzdog/solarized-osaka.nvim/commit/83b7026ac7a4e185d4ecbe99926fd94b5735e2ea, unless more improvements are expected? @Numkil
