### ISSUE TITLE
bug: snacks `opts.indent` visual mode selection.

### ISSUE THREAD

**Issue by Redoxahmii** [craftzdog/solarized-osaka.nvim#53]
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux

### Describe the bug

Visual discrepancies when using with `indent.scope`:
 
![2024-12-18-142112_hyprshot](https://github.com/user-attachments/assets/f57b3e1c-8e7c-4940-91e9-0791670ce961)

This [discussion](https://github.com/folke/snacks.nvim/issues/344) should provide further context.

Is solvable by changing `Visual` `inverse = false` but might not be desired that way.

### Steps To Reproduce

1. Select indented code in visual mode

### Expected Behavior

should properly reverse the selection.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by Redoxahmii** [comment]
From the discussion with the maintainer we would need to change the `Visual` highlight which can change how every color is marked when highlighted during visual mode.
- From this :
![2024-12-18-193302_hyprshot](https://github.com/user-attachments/assets/1856bf1e-5633-4a8a-a5d1-cb88e6c2c4f4)
- To this :
![image](https://github.com/user-attachments/assets/fc2f394e-af71-451b-a768-b28b0f435e2d)

The white artifact below the image is not theme issue.
If this is considered I will create a pull and merge.

**Comment by Redoxahmii** [comment]
This issue is also present when yanking text and setting `YankHighlight` explicitly does not seem to fix it.

**Comment by craftzdog** [comment]
Sure, I'll try `reverse = false` for a while and decide it.

**Comment by craftzdog** [comment]
I think `c.base02` works. `c.base03` was too dark for me.

**Comment by Redoxahmii** [comment]
Glad to know we think the same.
I will merge it for `Visual` but there is same issues when yanking text and it uses the highlight group of `IncSearch` which I think removing the `standout = true` part will make it subpar and should be bared with instead of changing.

**Comment by lihaochuanmei** [comment]
Excuse me.  How to disposition when at window?

**Comment by craftzdog** [comment]
got it, I changed it to `IncSearch = { fg = c.base2, bg = c.orange500 },` instead of using `standout = true`
