### ISSUE TITLE
bug: text on bg color unreadable 

### ISSUE THREAD

**Issue by AdrienLemaire** [craftzdog/solarized-osaka.nvim#7]
### Did you check docs and existing issues?

- [X] I have read all the tokyonight.nvim docs
- [X] I have searched the existing issues of tokyonight.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1811+gc95b9a32f

### Operating system/version

Ubuntu 22.04

### Describe the bug

![image](https://github.com/craftzdog/solarized-osaka.nvim/assets/260983/25042492-3871-41bc-bfb5-e41e8e859a5f)

I could verify that this problem occurs with or without tmux, on both Terminal and Alacritty.
I have true colors in the terminal.

I haven't modified the colorscheme config
```lua
return {
  "craftzdog/solarized-osaka.nvim",
  lazy = true,
  priority = 1000,
  opts = function()
    return {
      transparent = true,
    }
  end,
}
```

### Steps To Reproduce

Install LazyVim with your beautiful video.

### Expected Behavior

The text-on-bg should be readable

**Comment by craftzdog** [comment]
What is the highlight group for the tokens?
You can run `:Inspect` on one of them.

**Comment by AdrienLemaire** [comment]
I can't put my cursor directly on these strings, they are types generated by a typescript plugin. On the preceding character, I get:
```
Treesitter
  - @variable.tsx links to @variable tsx
  - @parameter.tsx links to @parameter tsx

Semantic Tokens
  - @lsp.type.parameter.typescriptreact links to @parameter priority: 125
  - @lsp.mod.declaration.typescriptreact links to @lsp priority: 126
  - @lsp.typemod.parameter.declaration.typescriptreact links to @lsp priority: 127

Extmarks
  - IlluminatedWordRead illuminate.highlight
  ```

**Comment by craftzdog** [comment]
I need to reproduce it.
what is the typescript plugin and configuration

**Comment by AdrienLemaire** [comment]
Sounds difficult to reproduce...
the lazy config has
```lua
{ import = "lazyvim.plugins.extras.lang.typescript" },
```
And I added `typescript-language-server` in the mason config in lsp.lua

![image](https://github.com/craftzdog/solarized-osaka.nvim/assets/260983/5b59e06d-bba3-42a2-89fd-e082a17de682)

関係ない話ですが、来週に一ヶ月大阪に行きますので、もし良かったら松山さんと会いたいです。LazyVimのビデオ設定は凄かったのでお礼でビールを一杯払ってあげたい。時間見つけれそうなら連絡先を教えて下さったら嬉しいです！

**Comment by AdrienLemaire** [comment]
I found the rule  by looking in `:highlight`
>  LspInlayHintxxx guifg=#576d74 guibg=#268bd3

![image](https://github.com/craftzdog/solarized-osaka.nvim/assets/260983/f428a17c-d7a7-4aa5-81df-da32c98a1aaf)

**Comment by craftzdog** [comment]
ah ok I wasn't on nvim 0.10 yet. will try it!

お誘いありがとうございます。いきなり個人的に会うのはお断りしています。大阪の旅を楽しんでください！

**Comment by craftzdog** [comment]
ok updated: https://github.com/craftzdog/solarized-osaka.nvim/commit/75e7315e5d7f76aa7e68f23cff0f5a7f1d09f2e7 https://github.com/craftzdog/solarized-osaka.nvim/commit/83b7026ac7a4e185d4ecbe99926fd94b5735e2ea
thanks for reporting
