### ISSUE TITLE
bug: Background is black using solarized-osaka

### ISSUE THREAD

**Issue by gudjonragnar** [craftzdog/solarized-osaka.nvim#8]
### Did you check docs and existing issues?

- [X] I have read all the tokyonight.nvim docs
- [X] I have searched the existing issues of tokyonight.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS Ventura 13.5.2

### Describe the bug

It seems like the background color is not set. 
<img width="1066" alt="image" src="https://github.com/craftzdog/solarized-osaka.nvim/assets/10629275/5a7423e6-0abc-470f-986d-ea71a945a391">
When I check the Normal highlight (which is what controls the background if I am not mistaken) i see this
```
:highlight Normal
Normal         xxx guifg=#9eabac
```
I tried this on both iTerm2 and newly installed WezTerm and had the same thing happen.
It also doesn't seem to happen with other colorschemes I have installed such as solarized (normal) and tokyonight.
The problem also exists on neovim 0.10.0 dev build

I don't know if this is an issue with my system or the colorscheme at this point. Do you have any ideas?

### Steps To Reproduce

`nvim -u repro.lua` with the minimal configuration results in the screenshot above

### Expected Behavior

The background should not be black (unless it should?)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("solarized-osaka")
-- add anything else here
```

**Comment by craftzdog** [comment]
Can't reproduce with `repro.lua`

**Comment by gudjonragnar** [comment]
Ok, thanks! Then it must be something with my setup 👍

**Comment by gudjonragnar** [comment]
It seems that setting `transparent = false` works. It seems that transparent is set to true as default in [config.lua](https://github.com/craftzdog/solarized-osaka.nvim/blob/fc026b879c1b6c0956c73731e56f74b85eee7d12/lua/solarized-osaka/config.lua#L9) but in the [README](https://github.com/craftzdog/solarized-osaka.nvim/blob/fc026b879c1b6c0956c73731e56f74b85eee7d12/README.md?plain=1#L74) it is set as false. I must have read the Readme as the default config.

**Comment by craftzdog** [comment]
good point, thanks!
